services:

  app:
    build: .
    container_name: laravel_app
    restart: unless-stopped
    volumes:
      - .:/var/www
      - vendor_data:/var/www/vendor
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_DATABASE: perelek
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend_default

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    networks:
      - backend_default
    environment:
      MYSQL_DATABASE: perelek
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    networks:
      - backend_default
    environment:
      PMA_HOST: mysql
    ports:
      - "8080:80"

  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n_automation
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - GENERIC_TIMEZONE=Asia/Jakarta
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - backend_default # Samakan dengan network yang dipakai mysql_db dan laravel

volumes:
  n8n_data:
  mysql_data:
  vendor_data:

networks:
  backend_default:
    driver: bridge
